<?php 
/**
 * Virtina
 * @package    Virtina_ProductSlider
 * @copyright  Copyright (c) 2015-2016 Virtina. (http://www.virtina.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */	
	$configNumber        =  $this->getConfigNumber();
	$configSlider        =  $this->getConfigSlider();
	$configPrice         =  $this->getConfigPrice();
	$configImage         =  $this->getConfigImage();
	$configTitle         =  $this->getConfigTitle();
	$configAuto          =  $this->getConfigAuto();
	$configSpeed         =  $this->getConfigSpeed();
	$configLoop          =  $this->getConfigLoop();
	$configNavigaton     =  $this->getConfigNavigaton();
	$configMaxCount      =  $this->getConfigMaxCount();
	$configTabCount      =  $this->getConfigTabCount();
	$configMobileCount   =  $this->getConfigMobileCount();
	$configCategoryId    =  $this->getConfigCategoryId();
	$configAddtoCart     =  $this->getConfigAddtoCart();
	$configProductTitle  =  $this->getConfigProductTitle();
	$configScrollCount   =  $this->getConfigScrollCount();
	$configProductRating =  $this->getConfigProductRating();
	$configTierPrice     =  $this->getConfigTierPrice();
				
	if($this->getSliderValue()){
		$sliderid = $this->getSliderValue();
	} else {
		$sliderid = "";
	}
	if($this->getCategoryId()){
		$categoryid = $this->getCategoryId();
	}else {
		$categoryid = $configCategoryId;
	}
	if($this->getProductCount()){
		$configNumber = $this->getProductCount();
	}
	if($this->getTabViewCount()){
		$configTabCount = $this->getTabViewCount();
	}

	if($this->getMobileViewCount()){
		$configMobileCount = $this->getMobileViewCount();
	}

	if($this->getScrollCount()){
		$configScrollCount = $this->getScrollCount();
	}

	if($this->getSliderTitle()){
		$configTitle = $this->getSliderTitle();
	}

	if($this->getSliderSpeed()){
		$configSpeed = $this->getSliderSpeed();
	}
?>		
<?php 
if($configSlider){ 				
	$collection = $this->getSliderProductCollection($categoryid);
	Mage::getSingleton('cataloginventory/stock')
					->addInStockFilterToCollection($collection);
	$this->_collection = $collection;
	$collection = $collection->setPageSize($configMaxCount);
	?>
	<?php if($collection->count() > 0) { ?>					

	<div class="widget widget-new-products productslider">	
		<h1><?php echo $this->__($configTitle) ?></h1>				
		<div class="widget-products" >
			<?php
				$_columnCount = 5; 
				$i = 0; 
			?>
			<ul class="products-custom-grid products-custom-grid--max-<?php echo $_columnCount; ?>-col-widget" id ="<?php echo $sliderid?$sliderid:'divId'; ?>">
				<?php foreach ($collection as $_product): ?>		
					<li class="item<?php if($i == 0): ?> first<?php elseif($i == ($_columnCount-1)): ?> last<?php endif; ?>">
						<!-- Product image -->
						<?php if($configImage):?>
							<a href="<?php echo $_product->getProductUrl() ?>">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(110); ?>" alt= "" />
							</a> 
						<?php endif ?>	
						<div class="product-info">
							<div class="inwrap"	>
									<!-- Product title -->
									<?php if($configProductTitle): ?>
										<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
									<?php endif ?>
									
									<!-- Product review -->									
									<?php if($configProductRating): ?>
										<?php echo $RatingOb = Mage::getModel('rating/rating')->getEntitySummary($_product->getId()); ?>
										<?php $ratings = $RatingOb->getSum()/$RatingOb->getCount(); ?>									
										<?php if($ratings): ?>
											<div class="ratings">
												<div class="rating-box">
													<div class="rating" style="width:<?php echo $ratings; ?>%"></div>
												</div>
											</div>
										<?php else : ?>
											<div class ="review_space" > &nbsp </div>
										<?php  endif ?>
									<?php endif ?>
									
									<!-- Product price -->
									<?php if($configPrice):
										 echo $this->getPriceHtml($_product, true, '-widget-new-grid'); 								                          
									endif ?>
									
									<!--Tier price with minimum price display -->
									<?php if($configTierPrice): ?>
										<div class="custom-price-box" >
											<?php 
												$my_tier_rocks = $this->getTierPrices($_product);
												if (!empty($my_tier_rocks)){
													$my_tier_rocks = $this->getTierPrices($_product); 
													$my_tier_rocks = $my_tier_rocks[0]['formated_price_incl_tax'];
												?>
													<span class = "my_tier price-including-tax">						
													  <span class = "label"><?php echo $this->__('As low as:') ?></span>
													  <span class = "price"><?=$my_tier_rocks?></span>				 
													</span>																
												<?php } ?>
												
										</div>
									<?php endif; ?>		
								</div>
							<!-- Add to cart button -->
							<div class="product-secondary">
								<?php if($configAddtoCart):?>
									<?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
										<p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
									<?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
										<p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
									<?php else: ?>
										<p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
								<?php endif; ?>
							</div>							
						</div>
					</li>		
				 <?php endforeach; ?>
			 </ul>
		</div>
 </div>
<script type="text/javascript">
    
 jQuery(document).ready(function(){ 
  <?php 
  if($sliderid){
		$idval = $sliderid;
	}
	else{
		$idval = 'divId';
	}
  ?>	
  jQuery('<?php echo "#".$idval ?>').slick({
	  dots		: false,
	  arrows	: <?php echo $configNavigaton?'true':'false' ;?>,
	  infinite	: <?php echo $configLoop?'true':'false' ;?>,
	  prevArrow	:'<img src="<?php echo $this->getSkinUrl('images/product-slider/previous.png') ?>" data-role="none" class="slick-prev" aria-label="Previous" tabindex="0" width="20" height="20">',
	  nextArrow	:'<img src="<?php echo $this->getSkinUrl('images/product-slider/next.png') ?>" data-role="none" class="slick-next" aria-label="Next" tabindex="0" width="20" height="20">',	  
	  speed		: <?php echo $configSpeed?$configSpeed:'700'; ?>,
	  autoplay 	: <?php echo $configAuto?'true':'false' ;?>,
	  slidesToShow	: <?php echo $configNumber?$configNumber:'5'; ?>,
	  slidesToScroll:<?php echo $configScrollCount?$configScrollCount:'3'; ?>,
	  responsive	: [
		{
		  breakpoint: 1024,
		  settings	: {
			slidesToShow	: 3,
			slidesToScroll	: 3,
			infinite		: true,
			dots			: false,
			dotsClass		:'slick-dots',
			draggable		: true,
			pauseOnHover	: true,
			swipe			: true,
			centerMode		: false
		  }
		},
		{
		  breakpoint: 600,
		  settings: {
			slidesToShow	: <?php echo $configTabCount?$configTabCount:'2'; ?>,
			slidesToScroll	: 2
		  }
		},
		{
		  breakpoint: 480,
		  settings: {
			slidesToShow	: <?php echo $configMobileCount?$configMobileCount:'1'; ?>,
			slidesToScroll	: 1
		  }
		}
	  ]
	});
});		
</script>
		<?php } ?>	
<?php } ?>
